[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt --no-cache-dir'
]

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --max-requests 100 --preload' 